name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check NodeJS version
        run: node -v
      - name: Check NPM version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check NodeJS version
        run: node -v
      - name: Check NPM version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATEDSA }}
      - name: Check SSH folder content
        run: ls -la ~/.ssh
      - name: Check NodeJS version
        run: node -v
      - name: rsync connection
        run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc * ${{secrets.USERDEV}}@${{secrets.SERVERDEV}}:/home/unang/nodejs-qae-github/
